title: gabs
description: 
author: Gabs
email: gaba@duck.com

assets: /assets
uploads: /uploads

permalink: /blog/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  - projects
  - bookmarks
  - contributions

navigation:
    - link: "/"
      name: Me
    - link: "/blog/"
      name: Blog
    - link: "/bookmarks/"
      name: Bookmarks
    - link: "/projects/"
      name: Projects
    - link: "/contributions/"
      name: Contributions
    - link: "emailto:gaba@duck.com"
      name: Email

plugins:
  - jekyll-feed